<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Automation</name>
   <tag></tag>
   <elementGuidId>dd3037da-554a-4853-8016-7698dbc328b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#filter_list > li > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='filter_list']/li/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a56d793-35ce-45dc-a317-b9831c4e1ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-value</name>
      <type>Main</type>
      <value>.automation</value>
      <webElementGuid>267fe4e6-cd0a-4c98-a923-9308d27b233a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation</value>
      <webElementGuid>4d734829-4b5b-4665-835c-f95da3e9d453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filter_list&quot;)/li[1]/div[1]</value>
      <webElementGuid>b6e98913-8e60-40d9-8151-3fafa5d2e560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames and Window Dummy Testing Site -_484b9f/iframe_br</value>
      <webElementGuid>8b253ec4-380f-40a7-9368-6a2f9ebfcdcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='filter_list']/li/div</value>
      <webElementGuid>41695c32-1695-42d0-8c03-d28fd85023cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/ul/li/div</value>
      <webElementGuid>fbb460b6-7f03-42f1-8e0b-2a86bbd0e2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Automation' or . = 'Automation')]</value>
      <webElementGuid>dfbccc81-171e-4b8a-90a4-8365169cb752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
