<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_br</name>
   <tag></tag>
   <elementGuidId>ab4c1908-7bad-4e86-9c9f-4beca5eb2f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;globalSqa&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='globalSqa']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6c8b086d-b0e6-4f5e-b70b-47e61a61072d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>800px</value>
      <webElementGuid>6dc38566-b1c5-473e-a15c-f717a735979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>500px</value>
      <webElementGuid>168233ee-c69b-451e-93f7-145d01792e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>globalSqa</value>
      <webElementGuid>002af7ab-3b90-450a-afa6-5cbf683a6868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f7035176-5d45-4a5b-b743-721939b56a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>abb9ba0b-df95-4670-98ea-cf8121212e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>6a1c05af-ba80-4423-a7e9-2b1c4a7ceeb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.globalsqa.com/trainings/</value>
      <webElementGuid>39676ac5-7a2a-468c-b70e-32f8f60e2b21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> lazyloaded</value>
      <webElementGuid>21664d93-05cb-48bd-9111-d475e0f37442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==</value>
      <webElementGuid>14b609da-1134-4c3c-9db1-af7f0a99f2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;br />
</value>
      <webElementGuid>ef821f08-ed79-4314-89e4-c4c9f33adde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-2632&quot;)/div[@class=&quot;twelve columns&quot;]/div[@class=&quot;newtabs horizontal&quot;]/div[@class=&quot;resp-tabs-container&quot;]/div[@class=&quot;single_tab_div resp-tab-content resp-tab-content-active&quot;]/p[1]/iframe[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>1838f21b-26c8-4f3c-858c-e3141cb97121</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='globalSqa']</value>
      <webElementGuid>df664ea0-78eb-4933-9ba9-938f46433735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='post-2632']/div[2]/div/div/div[3]/p/iframe</value>
      <webElementGuid>2060c383-4aec-4ef4-91f4-308e29eb7c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/iframe</value>
      <webElementGuid>60fc71f4-d250-4bd5-9740-fb57a063c07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'globalSqa' and @src = 'data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==' and (text() = '&lt;br />
' or . = '&lt;br />
')]</value>
      <webElementGuid>3f1ce77f-b2ab-41b2-a7e5-c9cde59c0944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
