<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_All</name>
   <tag></tag>
   <elementGuidId>2dd9698f-cb43-4da6-8a19-79beccccf992</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current_filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='current_filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>776d7f13-5319-403e-8fea-5f31f6919775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current_filter</value>
      <webElementGuid>178729b9-8f6a-408c-ae5a-3f75a021008d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All</value>
      <webElementGuid>bdd07d1d-94b2-4c87-ac30-1c60c199d0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current_filter&quot;)</value>
      <webElementGuid>313b4526-4e57-43b4-b333-548fe4e552c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames and Window Dummy Testing Site -_484b9f/iframe_br</value>
      <webElementGuid>22854e95-f921-4012-bac2-54e265815fd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='current_filter']</value>
      <webElementGuid>f1b1a286-fb91-4cf9-9330-d6ad8e8ef428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portfolio_filter']/span</value>
      <webElementGuid>1d3dfcbe-fc1e-4727-85f8-a3c33597b31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>97a29ae7-b402-4b63-b3c7-d47c54f12cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'current_filter' and (text() = 'All' or . = 'All')]</value>
      <webElementGuid>a7309deb-6760-45c5-a159-9b7f31123b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
