<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Automation</name>
   <tag></tag>
   <elementGuidId>e0b2f7dd-63e1-41c3-a2ea-385ee5ec3503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#current_filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='current_filter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b750f3a7-b911-47ba-bac0-94b09f222dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current_filter</value>
      <webElementGuid>bf1821a7-f65c-480f-8743-c5f6d82e8b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Automation</value>
      <webElementGuid>4a286eba-769b-4f83-be02-3bb95c60ce02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current_filter&quot;)</value>
      <webElementGuid>f2536771-377c-49b9-9dcb-069b4a6a74a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frames and Window Dummy Testing Site -_484b9f/iframe_br</value>
      <webElementGuid>aca06aa9-94b8-4065-9cc5-2a5dc46ad6fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='current_filter']</value>
      <webElementGuid>9ca6e584-76f1-43d9-95eb-79c389ecfd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portfolio_filter']/span</value>
      <webElementGuid>c5fdade6-4ad6-47da-a6ef-fa2fb8ef8721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>df520a76-4310-41fa-b34a-1dd743107f60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'current_filter' and (text() = 'Automation' or . = 'Automation')]</value>
      <webElementGuid>6c025d94-94f4-433a-a89f-3265e882e50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
